name: Daily Proverb Email

on:
  schedule:
    # Runs at 12:00 UTC (adjust as needed)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  send-proverb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          
      - name: Create config file with secrets
        run: |
          echo '{
            "email": {
              "sender_email": "${{ secrets.SENDER_EMAIL }}",
              "sender_password": "${{ secrets.EMAIL_PASSWORD }}",
              "recipient_email": "${{ secrets.RECIPIENT_EMAIL }}",
              "smtp_server": "smtp.gmail.com",
              "smtp_port": 587
            },
            "last_sent_date": "",
            "sent_proverbs": []
          }' > config.json
          
      - name: Run daily proverb script
        run: python daily_proverb.py
        
      - name: Commit changes to track sent proverbs
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add config.json
          git commit -m "Update sent proverbs tracking" || echo "No changes to commit"
          git push
